In [2]:
# Imports
import tensorflow as tf
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from random import randint

In [16]:
# Auxillary function to help with layer 2
def constFunc(values):
    ans = 0
    idealWeights = [0.3,0.1,-0.8,0.3,1.2]
    for i in range(len(values)):
        ans += values[i]*idealWeights[i]
    return ans + 0.1

# Random initialisation of weightMatrixLayer1 of dimensions 5x5
weightMatrixLayer1 = np.asarray(np.random.rand(5,5), dtype = np.float64)
print(weightMatrixLayer1)

# Ideal function (which is hoping to be mapped)
def calculate(inputAttributes):
    layer1 = np.matmul(inputAttributes,weightMatrixLayer1)
    layer2 = constFunc(layer1)
    return layer2

[[0.04725931 0.66077323 0.75338638 0.74618152 0.46225684]
 [0.11935399 0.32958983 0.4037058  0.84427089 0.24592834]
 [0.46346004 0.45129496 0.08452558 0.60918501 0.91462402]
 [0.33273352 0.17479756 0.88210738 0.59671884 0.68041874]
 [0.27044479 0.65296632 0.14386906 0.87835257 0.77949696]]


In [7]:
model = Sequential()
model.add(Dense(5, input_shape = (5,)))
model.add(Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 36
Trainable params: 36
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.get_weights()

[array([[ 0.13101053, -0.75829166,  0.7238418 , -0.13669217,  0.6460359 ],
        [ 0.13448179,  0.77050436,  0.01860243,  0.03432542,  0.25467408],
        [ 0.118595  ,  0.74407494, -0.47403875,  0.56489384,  0.13855153],
        [-0.43438244,  0.5228236 ,  0.07764447, -0.4264206 ,  0.6661713 ],
        [-0.02448499,  0.52841926, -0.3003494 ,  0.31233168,  0.06155604]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.96274996],
        [-0.4065895 ],
        [-0.44674444],
        [-0.6252513 ],
        [-0.8179972 ]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
# Data Generation for function mapping

x = []
y = []

for samples in range(100000):
    values = np.asarray(np.random.rand(5),dtype = np.float64)
    x.append(values)
    y.append(calculate(values))
print(len(x),"\n\n",x[:5])
print(len(y),"\n\n",y[:5])

100000 

 [array([0.79254344, 0.99007511, 0.99729002, 0.14353236, 0.68152173]), array([0.97744052, 0.67297249, 0.61736247, 0.09281006, 0.3376738 ]), array([0.18298575, 0.48624293, 0.73790139, 0.73374115, 0.73378138]), array([0.5424111 , 0.62114998, 0.1245201 , 0.56856274, 0.82733437]), array([0.43592993, 0.20759914, 0.79038336, 0.71369342, 0.67006172])]
100000 

 [2.8841889773810654, 1.8638850308529755, 2.522107949231879, 1.8448894146233976, 2.4916704704229544]


In [18]:
model.fit(x,y)

ValueError: Failed to find data adapter that can handle input: (<class 'list'> containing values of types {"<class 'numpy.ndarray'>"}), (<class 'list'> containing values of types {"<class 'numpy.float64'>"})

In [ ]:
# Training
model.compile(optimizer = 'adam', loss = 'mse')
trackingArray = []
for i in range(0,100000,15):
    model.fit(np.asarray(x[i:i+20]),np.asarray(y[i:i+20]))
    trackingArray.append(np.array(model.get_weights()))
print(len(trackingArray))

1/1 [==============================] - 0s 866us/step - loss: 3.0195


1/1 [==============================] - 0s 762us/step - loss: 0.6007


1/1 [==============================] - 0s 782us/step - loss: 0.1174


1/1 [==============================] - 0s 1ms/step - loss: 0.1570


1/1 [==============================] - 0s 852us/step - loss: 0.1010


1/1 [==============================] - 0s 788us/step - loss: 0.0908
