In [2]:
# Imports
import tensorflow as tf
import numpy as np
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from random import randint

In [6]:
# Auxillary function to help with layer 2
def constFunc(values):
    ans = 0
    idealWeights = [0.3,0.1,-0.8,0.3,1.2]
    for i in range(len(values)):
        ans += values[i]*idealWeights[i]
    return ans + 0.1

# Random initialisation of weightMatrixLayer1 of dimensions 5x5
weightMatrixLayer1 = np.random.rand(5,5)
print(weightMatrixLayer1)

# Ideal function (which is hoping to be mapped)
def calculate(inputAttributes):
    layer1 = np.matmul(inputAttributes,weightMatrixLayer1)
    layer2 = constFunc(layer1)
    return layer2

[[0.56384462 0.21598767 0.69767072 0.73068821 0.5441866 ]
 [0.58832017 0.0985392  0.65585671 0.02045132 0.77791374]
 [0.81376789 0.4737844  0.91857425 0.14786266 0.08459946]
 [0.22451021 0.1801326  0.6181986  0.25524443 0.19867362]
 [0.61778224 0.21400834 0.26414792 0.14911084 0.61991421]]


In [7]:
model = Sequential()
model.add(Dense(5, input_shape = (5,)))
model.add(Dense(1))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 5)                 30        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 6         
Total params: 36
Trainable params: 36
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.get_weights()

[array([[ 0.13101053, -0.75829166,  0.7238418 , -0.13669217,  0.6460359 ],
        [ 0.13448179,  0.77050436,  0.01860243,  0.03432542,  0.25467408],
        [ 0.118595  ,  0.74407494, -0.47403875,  0.56489384,  0.13855153],
        [-0.43438244,  0.5228236 ,  0.07764447, -0.4264206 ,  0.6661713 ],
        [-0.02448499,  0.52841926, -0.3003494 ,  0.31233168,  0.06155604]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.96274996],
        [-0.4065895 ],
        [-0.44674444],
        [-0.6252513 ],
        [-0.8179972 ]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
# Data Generation for function mapping

x = []
y = []

for samples in range(100):
    values = np.random.rand(5)
    x.append(values)
    y.append(calculate(values))
print(len(x),x)
print(len(y))

100
100
